openapi: 3.0.0

info:
    title: VirusTotal API
    description: VirusTotal API
    version: "v3"

servers:
    - url: https://virustotal.com/api/v3/

paths:
    /files/{hash}:
        get:
            operationId: lookupFileHash
            summary: Lookup File Hash information
            parameters:
                - in: path
                  name: hash
                  schema:
                      type: string
                  required: true
                  description: The hash to lookup
            responses:
                "200":
                    description: OK
                    content:
                        application/json:
                            schema:
